### ISSUE TITLE
Crash before mojang logo when using with optifine + optifabric

### ISSUE THREAD

**Issue by 7PkmnV** [burgerguy/HUDTweaks#14] opened 2021-09-14 16:08 UTC
When using the mod with optifine + optifabric, the game crashes before the mojang logo appears, with the following appearing on the launcher:

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

[crash-2021-09-14_11.05.33-client.txt](https://github.com/burgerguy/HUDTweaks/files/7163477/crash-2021-09-14_11.05.33-client.txt)

**Comment by burgerguy** [comment] 2021-09-18 22:49
Duplicate of #11, may fix this later but not right now

**Closed by burgerguy** 2021-09-18 22:49 UTC
